// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package fred.custom.crm.core.model.member;

import java.util.Date;

import fred.custom.crm.core.model.member.Person.Gender;

public class PersonBuilder extends PersonBuilderBase<PersonBuilder> {
    public static PersonBuilder person() {
        return new PersonBuilder();
    }

    public PersonBuilder() {
        super(new Person());
    }

    public Person build() {
        return getInstance();
    }
}

class PersonBuilderBase<GeneratorT extends PersonBuilderBase<GeneratorT>> {
    private Person instance;

    protected PersonBuilderBase(Person aInstance) {
        instance = aInstance;
    }

    protected Person getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withBirthDate(Date aValue) {
        instance.setBirthDate(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCellPhoneNumber(String aValue) {
        instance.setCellPhoneNumber(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withEmail(String aValue) {
        instance.setEmail(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withFirstName(String aValue) {
        instance.setFirstName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withGender(Gender aValue) {
        instance.setGender(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withId(Long aValue) {
        instance.setId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLastName(String aValue) {
        instance.setLastName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSocialInsuranceNumber(String aValue) {
        instance.setSocialInsuranceNumber(aValue);

        return (GeneratorT) this;
    }
}
